.MODEL TINY
.DATA
    BRIGHTRED   DB  04H ;PIXEL COLOR
    BRIGHTBLUE  DB  03H
    BEGINREDROW DW  140
    BEGINREDCOL DW  140
    ENDREDROW       DW  240
    ENDREDCOL       DW  240
    BEGINBLUEROW    DW  40
    BEGINBLUECOL    DW  40
    ENDBLUEROW      DW  140
    ENDBLUECOL      DW  140
    ORIGINAL    DB  ?
    
.CODE
.STARTUP    

    MOV AH, 0FH ;GETTING THE DISPLAY MODE
    INT 10H
    
    MOV ORIGINAL,AL ;PRESERVING THE ORIGINAL VALUE OF AL
    MOV AL, 12H ;SETTING THE DISPLAY MODE TO GRAPHICAL MODE
    MOV AH, 0
    INT 10H
    
    MOV DX, BEGINREDROW ;INITIALISING THE BEGINNING
    
X1: MOV CX, BEGINREDCOL ;INITIALISING THE COLUMN POSITION

X2: MOV AL, BRIGHTRED ;PIXEL COLOR
    MOV AH, 0CH ;FILLING A PIXEL
    INT 10H
    
    INC CX
    CMP CX, ENDREDCOL
    JNZ X2 ; IF THE COLUMN IS NOT COMPLETED
    
    INC DX ;JUMP TO THE NEXT ROW
    CMP DX, ENDREDROW
    JNZ X1 ;START FROM THE NEXT ROW


    MOV DX, BEGINBLUEROW ;INITIALISING THE BEGINNING
    
X4: MOV CX, BEGINBLUECOL ;INITIALISING THE COLUMN POSITION

X5: MOV AL, BRIGHTBLUE ;PIXEL COLOR
    MOV AH, 0CH ;FILLING A PIXEL
    INT 10H
    
    INC CX
    CMP CX, ENDBLUECOL
    JNZ X5 ; IF THE COLUMN IS NOT COMPLETED
    
    INC DX ;JUMP TO THE NEXT ROW
    CMP DX, ENDBLUEROW
    JNZ X4 ;START FROM THE NEXT ROW
    
X3: MOV AH, 07H
    INT 21H 
    CMP AL,'E' ;PRESS 'E' FOR EXIT
    JZ X3

    MOV AL, ORIGINAL ;RESTORING BACK THE ORGINAL DISPLAY MODE
    MOV AH, 0
    INT 10H
    
.EXIT
END