.model tiny
.386
.data
	FILE1	    DB	'FILE_1.txt',0
    FILE2	    DB	'FILE_2.txt',0
	FIRSTNAME	DB	'Dhruv'
    NEWLINE1    DB	0DH, 0AH
    LASTNAME	DB	'Rawat'
    NEWLINE2    DB	0DH, 0AH
	IDNO	    DB	'2019B3A70537P$'
    NEWLINE	    DB	0DH, 0AH,'$'
	STORE	    DB	100 DUP('0')
    DISPLAY	    DB	100 DUP('0')
    PROMPT1     DB	'FILE_1 CONTENTS: ',0DH, 0AH,'$',0
    PROMPT2     DB	'FILE_2 CONTENTS AFTER COPY: ',0DH, 0AH,'$',0

.code
.startup
	
	;CREATING THE FILE_1
	MOV	AH, 3CH 
	LEA	DX,	FILE1
	MOV CL, 1;
	INT 21H
	
	;OPENING THE FILE_1
	LEA DX, FILE1
	MOV AH, 3DH
	MOV AL, 02H
	INT 21H
	
	;WRITING THE STRINGS INTO THE FILE_1 IN 3 LINES
	MOV BX,AX ;TRANSFERRING THE FILE HANDLE
	MOV AH, 40H
	MOV	CX,	27
	LEA	DX, FIRSTNAME 
	INT 21H

	;DISPLAYING FILE_1 CONTENTS
    MOV	AH, 09H
	LEA	DX, PROMPT1
	INT 21H

    MOV	AH, 09H
	MOV	CX,	11
	LEA	DX, FIRSTNAME
	INT 21H

    MOV	AH, 09H
	LEA	DX, NEWLINE
	INT 21H
    
    ;CLOSING THE FILES
	MOV AH, 3EH 
	INT 21H
    
    ;CREATING THE FILE_2
	MOV	AH, 3CH 
	LEA	DX,	FILE2
	MOV CL, 1;
	INT 21H

    ;OPENING THE FILE_1 FOR READING
	LEA DX, FILE1
	MOV AH, 3DH
	MOV AL, 00H
	INT 21H

    ;READING DATA FROM THE FILE BYTE BY BYTE
	MOV BX, AX
	LEA	DX, STORE

 X1:MOV	CX,	01
	MOV AH, 3FH	
	INT 21H
	INC DX
	CMP	AX,00H
	JNZ X1
	
	MOV DI, DX
	MOV AH, '$'
	MOV [DI-1],AH
	
	;CLOSING THE FILE	
	MOV AH, 3EH 
	INT 21H

    ;OPENING THE FILE_2 FOR WRITING
	LEA DX, FILE2 
	MOV AH, 3DH
	MOV AL, 02H ;WRITE/READ
	INT 21H

    MOV AH, 40H 
	MOV	CX,	27
	LEA	DX, STORE 
	INT 21H
	
    ;CLOSING THE FILE	
	MOV AH, 3EH 
	INT 21H

    ;OPENING THE FILE_2 FOR READING
	LEA DX, FILE2 
	MOV AH, 3DH
	MOV AL, 00H ;READING
	INT 21H
	
	;READING DATA FROM THE FILE
	MOV BX, AX
	LEA	DX, DISPLAY
	
X2: MOV	CX,	01
	MOV AH, 3FH	
	INT 21H
	INC DX
	CMP	AX,00
	JNZ X2
	
	MOV DI, DX
	MOV AH, '$'
	MOV [DI-1],AH
	
    MOV	AH, 09H
	LEA	DX, PROMPT2
	INT 21H

	;DISPLAY THE DATA
	MOV AH, 09H
	LEA DX, DISPLAY
	INT 21H
	
	;CLOSING THE FILE	
	MOV AH, 3EH 
	INT 21H

.exit
end